-- TikGrab 5.2 — public reviews
-- Run this in Supabase SQL Editor.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  rating integer not null check (rating between 1 and 5),
  name text not null default 'Pengguna TikGrab',
  review_text text not null check (char_length(review_text) between 1 and 300),
  status text not null default 'published' check (status in ('published','hidden')),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

revoke all on table public.reviews from anon, authenticated;
grant select, insert on table public.reviews to anon;

drop policy if exists "Public can read published reviews" on public.reviews;
create policy "Public can read published reviews"
on public.reviews for select
to anon
using (status = 'published');

drop policy if exists "Public can submit reviews" on public.reviews;
create policy "Public can submit reviews"
on public.reviews for insert
to anon
with check (
  rating between 1 and 5
  and char_length(review_text) between 1 and 300
  and char_length(name) between 1 and 40
  and status = 'published'
);

create index if not exists reviews_created_at_idx on public.reviews (created_at desc);
create index if not exists reviews_status_created_at_idx on public.reviews (status, created_at desc);
